SELECT * FROM T_SIP_DEPARTAMENTO;

INSERT INTO T_SIP_DEPARTAMENTO VALUES (1, 'FINANCEIRO', 'FIN');
INSERT INTO T_SIP_DEPARTAMENTO VALUES (2, 'MARKETING', 'MKT');
INSERT INTO T_SIP_DEPARTAMENTO VALUES (3, 'RECURSOS HUMANOS', 'RHU');

COMMIT;