-- COUNT()
SELECT * FROM T_SIP_FUNCIONARIO;
SELECT COUNT(*) FROM T_SIP_FUNCIONARIO;

SELECT * FROM T_SIP_PROJETO;
SELECT COUNT(DT_TERMINO) FROM T_SIP_PROJETO;

  -- Contando as linhas onde não há data do termino do projeto
SELECT COUNT(CD_PROJETO) 
    FROM T_SIP_PROJETO
    WHERE DT_TERMINO IS NULL;

  -- COUNT - cláusula DISTINCT
SELECT * FROM T_SIP_IMPLANTACAO;

SELECT COUNT(CD_PROJETO)
  FROM T_SIP_IMPLANTACAO;

 SELECT COUNT(DISTINCT CD_PROJETO)
  FROM T_SIP_IMPLANTACAo;

-- SUM()
SELECT * FROM T_SIP_FUNCIONARIO;
SELECT SUM(VL_SALARIO_MENSAL) FROM T_SIP_FUNCIONARIO;

-- AVG() - Média Aritmética
SELECT * FROM T_SIP_FUNCIONARIO;
SELECT AVG(VL_SALARIO_MENSAL) FROM T_SIP_FUNCIONARIO;

-- MIN()
SELECT * FROM T_SIP_FUNCIONARIO;
SELECT MIN(VL_SALARIO_MENSAL) FROM T_SIP_FUNCIONARIO;

-- MAX()
SELECT * FROM T_SIP_FUNCIONARIO;
SELECT MAX(VL_SALARIO_MENSAL) FROM T_SIP_FUNCIONARIO;

-- STDDEV() - Devio Padrão
SELECT * FROM T_SIP_FUNCIONARIO;
SELECT STDDEV(VL_SALARIO_MENSAL) FROM T_SIP_FUNCIONARIO;

-- VARIANCE() - Variância
SELECT * FROM T_SIP_FUNCIONARIO;
SELECT VARIANCE(VL_SALARIO_MENSAL) FROM T_SIP_FUNCIONARIO;

-- GROUP BY

SELECT NR_MATRICULA, 
    COUNT(CD_DEPENDENTE) "QTDE DEPENDENTES"
  FROM T_SIP_DEPENDENTE
  GROUP BY NR_MATRICULA
;

SELECT CD_DEPTO,
    COUNT(NR_MATRICULA) "QTDE. FUNCIONARIOS NO DEPTO",
    SUM(VL_SALARIO_MENSAL) "TOTAL SALARIO POR DEPTO",
    ROUND(AVG(VL_SALARIO_MENSAL),2) "MEDIA SALARIAL POR DEPTO"
  FROM T_SIP_FUNCIONARIO
  GROUP BY CD_DEPTO
  ORDER BY CD_DEPTO
;

-- EXEMPLO – GROUP BY COM VÁRIAS TABELAS
SELECT F.NM_FUNCIONARIO       "FUNCIONARIO" ,
    D.NR_MATRICULA         "MATRICULA"   , 
      COUNT(D.NR_MATRICULA)  "QTDE. DEPENDENTES"
  FROM T_SIP_FUNCIONARIO F INNER JOIN T_SIP_DEPENDENTE D
  ON (F.NR_MATRICULA = D.NR_MATRICULA)
  GROUP BY F.NM_FUNCIONARIO, D.NR_MATRICULA
;

-- EXEMPLO – INSTRUÇÃO CASE
SELECT
  NM_PROJETO,
  DT_TERMINO,
CASE
  WHEN DT_TERMINO IS NULL THEN 'EM ANDAMENTO'
  ELSE 'FINALIZADO'
END STATUS_PROJETO
  FROM T_SIP_PROJETO
  ORDER BY NM_PROJETO
;