INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SG_DEPTO)
    VALUES (1, 'FINANCEIRO','FIN');

SELECT * FROM T_SIP_DEPARTAMENTO;

-- Inserindo uma data ORACLE

INSERT INTO t_sip_projeto 
    VALUES (1, 'PROJETO ABC', 
        TO_DATE('18/12/2024','DD/MM/YYYY'),
        TO_DATE('29/12/2024','DD/MM/YYYY'));

SELECT * FROM T_SIP_PROJETO;

-- INSERÇÃO COM MANIPULAÇÃO DE NÚMEROS DECIMAIS

INSERT INTO T_SIP_FUNCIONARIO
    VALUES (12345,1,'JOÃO DA SILVA XAVIER', 
        TO_DATE('18/03/1985','DD/MM/YYYY'),
        TO_DATE('21/07/2012','DD/MM/YYYY'),
        'AVENIDA PAULISTA, 1900 - 10o. ANDAR', 
        1234.56); -- UTILIZAMOS O PONTO DECIMAL

SELECT * FROM T_SIP_FUNCIONARIO;