-- CONVERSÃO DE CARACTERES
SELECT F.NM_FUNCIONARIO "ATUAL",
    LOWER(F.NM_FUNCIONARIO) "MINUSCULAS",
    UPPER(F.NM_FUNCIONARIO) "MAIUSCULA",
    INITCAP(F.NM_FUNCIONARIO) "MAIUSCULA/MINUSCULA "
FROM T_SIP_FUNCIONARIO F;

